import json

with open('data/fragen.json', encoding='utf-8') as f:
    data = json.load(f)

q = '„'
e = '"'

def zitat(inhalt, quelle, link):
    return {"text": q + inhalt + e, "quelle": quelle, "link": link}

def mc(id, sw, frage, antworten, richtig, erklaerung, bibelstelle=None, bibellink=None):
    return {
        "id": id, "typ": "multiple-choice", "schwierigkeit": sw,
        "frage": frage, "antworten": antworten, "richtig": richtig,
        "erklaerung": erklaerung, "bibelstelle": bibelstelle, "bibellink": bibellink
    }

neue_fragen = {

"pfingsten": [
    mc("pf8", 2,
        "Woher kamen die Menschen, die die Jünger an Pfingsten in ihrer Sprache reden hörten?",
        ["Nur aus Jerusalem und den umliegenden Dörfern Judäas",
         "Aus vielen Völkern der Welt: Parthern, Medern, Ägyptern und anderen",
         "Aus den drei großen Städten: Rom, Athen und Alexandria",
         "Aus den zwölf Stämmen Israels, die zum Fest nach Jerusalem gepilgert waren"],
        1,
        "Lukas listet in Apg 2 eine beeindruckende Völkerliste auf: Parther, Meder, Elamiter, Bewohner Mesopotamiens, Judäas, Kappadoziens, Ägyptens, Libyens, Roms, Kretas, Arabiens... Das unterstreicht: Die Botschaft des Evangeliums ist von Anfang an für alle Völker bestimmt.",
        "Apg 2,9-11", "https://www.die-bibel.de/bibel/BB/ACT.2.9-ACT.2.11"),
    mc("pf9", 2,
        "Was tat Petrus unmittelbar nach dem Pfingstgeschehen?",
        ["Er zog sich in den Tempel zurück, um in Stille zu beten",
         "Er hielt eine öffentliche Predigt und erklärte das Geschehen als Erfüllung der Prophetie",
         "Er schrieb einen Brief an die Gemeinden in den umliegenden Städten",
         "Er lud die Menge ein, am nächsten Morgen wiederzukommen"],
        1,
        "Petrus — der wenige Wochen zuvor Jesus dreimal verleugnet hatte — trat nun mutig vor die Menge und predigte. Er zitierte den Propheten Joel und rief: Jesus von Nazareth ist der verheißene Christus, auferstanden und erhöht! Rund 3.000 Menschen ließen sich daraufhin taufen. (Apg 2,14–41)",
        "Apg 2,14-41", "https://www.die-bibel.de/bibel/BB/ACT.2.14-ACT.2.41"),
    mc("pf10", 3,
        "Was versteht die Theologie unter »Glossolalie«?",
        ["Das stille, meditative Beten ohne Worte in der Gemeinschaft",
         "Das laute, gemeinsame Vorlesen der Heiligen Schrift im Gottesdienst",
         "Das Reden in unverständlichen Zungen als besondere Gabe des Heiligen Geistes",
         "Das gemeinschaftliche Sprechen des Glaubensbekenntnisses in der Liturgie"],
        2,
        "Glossolalie (griech. glossa = Zunge, lalein = reden) bezeichnet das ekstatische Reden in unverständlichen Lauten als Zeichen des Heiligen Geistes. Paulus kennt diese Gabe, mahnt aber: Im Gottesdienst soll jemand übersetzen, damit alle etwas davon haben (1 Kor 14). Beim Pfingstgeschehen dagegen verstehen alle in ihrer eigenen Sprache — das ist etwas anderes.",
        "1 Kor 14,2", "https://www.die-bibel.de/bibel/BB/1CO.14.2-1CO.14.2"),
],

"gemeinde": [
    mc("ge8", 1,
        "Was sind die zwei Sakramente der evangelischen Kirche?",
        ["Taufe und Abendmahl",
         "Taufe und Konfirmation",
         "Abendmahl und Beichte",
         "Taufe und kirchliche Trauung"],
        0,
        "Die evangelische Kirche kennt zwei Sakramente: Taufe und Abendmahl. Luther orientierte sich daran, dass Jesus diese beiden Handlungen selbst eingesetzt hat. Die katholische Kirche kennt sieben Sakramente — z. B. auch Firmung, Beichte, Ehe, Priesterweihe und Krankensalbung.",
        None, None),
    mc("ge9", 2,
        "Was bedeutet das Wort »Ökumene«?",
        ["Die Einheit aller evangelischen Kirchengemeinden Deutschlands",
         "Die Gemeinschaft aller christlichen Kirchen und Konfessionen weltweit",
         "Der Dialog zwischen Christentum und anderen Weltreligionen",
         "Die Zusammenarbeit von Kirche und Staat in sozialen Fragen"],
        1,
        "Ökumene kommt vom griechischen oikoumene — die bewohnte Erde. Es bezeichnet die Bewegung zur Einheit aller Christen über Konfessionsgrenzen hinweg: evangelisch, katholisch, orthodox. Der Ökumenische Rat der Kirchen (gegründet 1948 in Amsterdam) ist heute mit über 350 Mitgliedskirchen das wichtigste Forum.",
        None, None),
    mc("ge10", 3,
        "Was ist der Unterschied zwischen »Ortsgemeinde« und »Kirche« im theologischen Sinn?",
        ["Die Ortsgemeinde feiert Gottesdienst; die Kirche ist das Gebäude, in dem sie sich trifft",
         "Die Ortsgemeinde ist eine konkrete Gemeinschaft vor Ort; Kirche (griech. ekklesia) meint die weltweite Gemeinschaft aller Glaubenden",
         "Die Ortsgemeinde gehört zum Kirchenkreis; Kirche ist die übergeordnete Landeskirche",
         "Die Ortsgemeinde besteht aus Gemeindemitgliedern; Kirche umfasst nur die ordinierten Amtsträger"],
        1,
        "Ekklesia (griech.) bedeutet »die Herausgerufenen«. Im NT meint es sowohl die konkrete Gemeinde vor Ort als auch die universale Kirche Jesu Christi. Martin Luther betonte: Die Kirche ist »das Volk Gottes« — alle Getauften, nicht eine Institution. Jede Ortsgemeinde ist deshalb »ganze Kirche« an einem bestimmten Ort.",
        None, None),
],

"bibel": [
    mc("bi8", 1,
        "Wie viele Bücher hat die Bibel in der evangelischen Zählung?",
        ["39 Bücher im Alten und Neuen Testament zusammen",
         "54 Bücher, davon 27 im Alten und 27 im Neuen Testament",
         "66 Bücher: 39 im Alten und 27 im Neuen Testament",
         "73 Bücher: 46 im Alten und 27 im Neuen Testament"],
        2,
        "Die evangelische Bibel umfasst 66 Bücher: 39 im Alten Testament und 27 im Neuen Testament. Die katholische Bibel enthält zusätzlich 7 sogenannte deuterokanonische Bücher (z. B. Judit, Tobias, 1. und 2. Makkabäer), die Protestanten als »Apokryphen« bezeichnen. Die Zählung unterscheidet sich also je nach Konfession.",
        None, None),
    mc("bi9", 2,
        "Wer schrieb die meisten Briefe im Neuen Testament?",
        ["Johannes, der Lieblingsjünger Jesu",
         "Petrus, der erste unter den Aposteln",
         "Paulus, der Apostel der Völker",
         "Jakobus, der Bruder Jesu"],
        2,
        "Paulus verfasste mindestens 13 der 27 neutestamentlichen Schriften — Briefe an Gemeinden in Korinth, Rom, Galatien, Philippi u. a. Paulus war ursprünglich Verfolger der Christen, wurde durch eine Erscheinung des Auferstandenen bekehrt und wurde zum bedeutendsten Missionar der frühen Kirche.",
        None, None),
    mc("bi10", 3,
        "Was ist die Septuaginta?",
        ["Die lateinische Übersetzung der gesamten Bibel, entstanden ca. 400 n. Chr.",
         "Die aramäische Übersetzung der Psalmen für den Synagogengottesdienst",
         "Die griechische Übersetzung des Alten Testaments, entstanden ca. 250 v. Chr.",
         "Die hebräische Neuschrift des Alten Testaments mit Vokalzeichen, ca. 500 n. Chr."],
        2,
        "Die Septuaginta (lat. für 70, abgekürzt LXX) entstand ab ca. 250 v. Chr. in Alexandria für jüdische Gemeinden, die kein Hebräisch mehr sprachen. Der Legende nach übersetzten 70 Gelehrte unabhängig voneinander und kamen zum selben Ergebnis. Das Neue Testament zitiert das Alte Testament meistens nach der Septuaginta.",
        None, None),
],

"jesus-historisch": [
    mc("jh8", 1,
        "Wie alt war Jesus ungefähr, als er seinen öffentlichen Dienst begann?",
        ["Etwa 20 Jahre alt",
         "Etwa 30 Jahre alt",
         "Etwa 40 Jahre alt",
         "Etwa 50 Jahre alt"],
        1,
        "Laut Lk 3,23 begann Jesus seinen Dienst »mit ungefähr 30 Jahren«. Das Alter 30 hatte im Judentum symbolische Bedeutung — Leviten traten ihren Tempeldienst mit 30 an (4. Mose 4,3). Historisch ist das exakte Alter nicht gesichert; auch das Geburtsjahr Jesu ist umstritten (wahrscheinlich zwischen 7 und 4 v. Chr.).",
        "Lk 3,23", "https://www.die-bibel.de/bibel/BB/LUK.3.23-LUK.3.23"),
    mc("jh9", 2,
        "Was bedeutet der Titel »Rabbi«, mit dem Jesus oft angesprochen wurde?",
        ["Heiliger / Gesalbter des Herrn",
         "Lehrer / Meister",
         "Wundertäter / Heiler",
         "Sohn Gottes / Messias"],
        1,
        "Rabbi (hebr.) bedeutet wörtlich »mein Großer« und war ein Ehrentitel für angesehene jüdische Lehrer. Jesus wurde so angesprochen, obwohl er keine offizielle Rabbiner-Ausbildung hatte — was manche verwunderte: »Woher hat dieser die Weisheit?« (Mt 13,54). Er lehrte »mit Vollmacht, nicht wie die Schriftgelehrten« (Mk 1,22).",
        None, None),
    mc("jh10", 3,
        "Was ist die Bergpredigt — und wo gibt es bei Lukas eine Parallelversion?",
        ["Jesu Abschiedsrede an die Jünger (Joh 14–17); keine Parallele in anderen Evangelien",
         "Jesu zentrale Lehrrede (Mt 5–7); bei Lukas gibt es eine kürzere »Feldrede« (Lk 6,17–49)",
         "Jesu erste Predigt in Nazareth (Lk 4); bei Matthäus als Synagogenpredigt erzählt",
         "Jesu Predigt im Tempel vor der Passion (Mt 21); bei Markus als Streitgespräch"],
        1,
        "Die Bergpredigt (Mt 5–7) ist Jesu umfangreichste Lehrrede, gehalten auf einem Berg in Galiläa. Bei Lukas gibt es eine kürzere Parallelversion — die »Feldrede« (Lk 6,17–49), gehalten auf einer ebenen Fläche. Wichtig: Das Vaterunser fehlt in der Feldrede — bei Lukas steht es an anderer Stelle (Lk 11,1–4), als Antwort auf eine Frage der Jünger.",
        "Mt 5,1-7,29", "https://www.die-bibel.de/bibel/BB/MAT.5.1-MAT.7.29"),
],

"jesus-christus": [
    mc("jc8", 1,
        "Was feiern Christen an Weihnachten?",
        ["Die Taufe Jesu im Jordan durch Johannes den Täufer",
         "Die Menschwerdung Gottes — die Geburt Jesu von Nazareth",
         "Die Auferstehung Jesu von den Toten am dritten Tag",
         "Den Einzug Jesu in Jerusalem auf einem Esel"],
        1,
        "Weihnachten feiert die Geburt Jesu — also die Menschwerdung Gottes. Der 25. Dezember ist nicht Jesu historischer Geburtstag. Die frühe Kirche legte das Fest auf dieses Datum, das im römischen Kalender mit der Wintersonnenwende zusammenfiel und dem Fest Sol Invictus (»Unbesiegte Sonne«) entsprach. Jesus als »Licht der Welt« — das passte theologisch perfekt.",
        None, None),
    mc("jc9", 2,
        "Was ist Christi Himmelfahrt?",
        ["Das Fest der Taufe Jesu, am ersten Sonntag nach Epiphanias",
         "Das Fest der Auferstehung Jesu, 50 Tage vor Pfingsten",
         "Das Fest der Rückkehr Jesu zum Vater, 40 Tage nach Ostern",
         "Das Fest der Geburt Jesu, am 25. Dezember"],
        2,
        "Christi Himmelfahrt wird 40 Tage nach Ostern gefeiert (immer ein Donnerstag). Jesus erschien nach der Auferstehung noch 40 Tage seinen Jüngern — dann »wurde er vor ihren Augen emporgehoben« (Apg 1,9). Theologisch bedeutet es: Jesus ist nicht mehr lokal gebunden, sondern »zur Rechten des Vaters« — überall und für alle erreichbar.",
        "Apg 1,9", "https://www.die-bibel.de/bibel/BB/ACT.1.9-ACT.1.9"),
    mc("jc10", 3,
        "Was meint »Präexistenz« Jesu?",
        ["Jesus existierte nach seiner Auferstehung weiter bei Gott im Himmel",
         "Jesus existierte schon vor seiner Geburt als Mensch von Ewigkeit her bei Gott",
         "Jesus wurde von Maria empfangen, bevor sie mit Josef zusammenlebte",
         "Jesus kannte als Gottessohn alle zukünftigen Ereignisse schon im Voraus"],
        1,
        "Das Johannesevangelium beginnt: »Im Anfang war das Wort — und das Wort war Gott« (Joh 1,1). Diese Aussage löste heftige Debatten aus: Der Theologe Arius (4. Jh.) lehrte, Jesus sei eine Schöpfung Gottes. Das Konzil von Nicäa (325) entschied dagegen: Jesus ist »wesensgleich« mit dem Vater (griech. homoousios) — ewig, nicht geschaffen. Die Christologie bleibt bis heute ein zentrales Diskussionsfeld der Theologie.",
        "Joh 1,1", "https://www.die-bibel.de/bibel/BB/JHN.1.1-JHN.1.1"),
],

"jesu-worte": [
    mc("jw8", 1,
        "Was sind die »Ich bin«-Worte Jesu im Johannesevangelium?",
        ["Gebete Jesu, in denen er sich an Gott als seinen Vater wendet",
         "Selbstaussagen Jesu wie »Ich bin das Licht«, »der Weg«, »die Wahrheit«, »das Leben«",
         "Gleichnisse, in denen Jesus von Weinstock, Brot und Hirten spricht",
         "Aufrufe Jesu an die Jünger: »Ich bin gesandt — ihr werdet es auch sein«"],
        1,
        "Im Johannesevangelium gibt es sieben »Ich bin«-Worte Jesu: »Ich bin das Brot des Lebens«, »das Licht der Welt«, »die Tür«, »der gute Hirte«, »die Auferstehung und das Leben«, »der Weg, die Wahrheit und das Leben« und »der wahre Weinstock«. Sie erinnern an den Gottesnamen »Ich bin, der ich bin« (2. Mose 3,14) — eine hohe Aussage über Jesus.",
        None, None),
    mc("jw9", 2,
        "Was meinte Jesus mit »Selig sind die Sanftmütigen, denn sie werden das Erdreich besitzen«?",
        ["Wer körperlich schwach ist, bekommt von Gott besondere Fürsorge und Schutz",
         "Wer nicht auf Gewalt setzt, sondern auf Gott vertraut, gehört zu Gottes Reich",
         "Wer auf seinen Besitz verzichtet, wird im Jenseits mit Reichtum belohnt",
         "Wer bescheiden auftritt und wenig redet, wird von Menschen respektiert"],
        1,
        "»Sanftmut« ist im biblischen Sinne nicht Schwäche, sondern bewusster Gewaltverzicht und Vertrauen auf Gott statt auf Macht. »Das Erdreich besitzen« nimmt Ps 37,11 auf: Die Sanftmütigen, nicht die Mächtigen, werden am Ende das Land erben. Jesus dreht die Wertemaßstäbe der Welt um — eine der kühnsten Aussagen der Bergpredigt.",
        "Mt 5,5", "https://www.die-bibel.de/bibel/BB/MAT.5.5-MAT.5.5"),
    mc("jw10", 3,
        "Was meinte Jesus mit dem Gleichnis vom Schalksknecht (Mt 18,23–35)?",
        ["Wer Schulden macht, soll das Gericht fürchten und seine Pflichten erfüllen",
         "Wer selbst Vergebung empfangen hat und sie anderen verweigert, handelt gegen Gottes Wesen",
         "Wer seinem König treu dient, wird am Ende reich belohnt und freigelassen",
         "Wer anderen vergibt, muss selbst keine Strafe mehr fürchten und wird frei"],
        1,
        "Der Knecht wird von seinem König von einer riesigen Schuld befreit — und lässt dann seinen eigenen Schuldner ins Gefängnis werfen. Das empört sogar die Mitknechte. Jesus schließt: Wer die empfangene Vergebung nicht weitergibt, versteht Gottes Gnade nicht. Direkt anlass der Frage des Petrus: »Wie oft soll ich vergeben?« — »Nicht siebenmal, sondern siebenundsiebzigmal.«",
        "Mt 18,23-35", "https://www.die-bibel.de/bibel/BB/MAT.18.23-MAT.18.35"),
],

"jesu-taten": [
    mc("jt8", 1,
        "Bei welcher Hochzeit vollbrachte Jesus sein erstes Wunder?",
        ["Bei der Hochzeit von Simon und Maria in Kapharnaum",
         "Bei der Hochzeit in Kana in Galiläa",
         "Bei der Hochzeit des Zachäus in Jericho",
         "Bei der Hochzeit am Ufer des Sees Gennesaret"],
        1,
        "Das erste Wunder Jesu war die Verwandlung von Wasser in Wein bei einer Hochzeit in Kana (Joh 2,1–11). Maria, die Mutter Jesu, weist ihn darauf hin, dass der Wein ausgeht. Johannes nennt es ein »Zeichen« — nicht nur ein Wunder, sondern ein Hinweis auf Jesu Herrlichkeit. Die Jünger glaubten an ihn.",
        "Joh 2,1-11", "https://www.die-bibel.de/bibel/BB/JHN.2.1-JHN.2.11"),
    mc("jt9", 2,
        "Was tat Jesus, als er zum Grab des Lazarus kam und Maria weinte?",
        ["Er betete laut und rief Gott um Kraft für das Wunder an",
         "Er weinte selbst — und rief Lazarus dann ins Leben zurück",
         "Er tröstete Maria mit Worten und bat die Menge, sich zu entfernen",
         "Er forderte alle Anwesenden auf, den Stein wegzurollen"],
        1,
        "»Jesus weinte« (Joh 11,35) — der kürzeste Vers der Bibel, und einer der bedeutsamsten. Er zeigt: Jesus ist nicht unbewegt, er leidet mit. Dann ruft er mit lauter Stimme: »Lazarus, komm heraus!« Die Geschichte steht im Johannesevangelium als letztes und größtes Zeichen vor dem Einzug in Jerusalem.",
        "Joh 11,35", "https://www.die-bibel.de/bibel/BB/JHN.11.35-JHN.11.35"),
    mc("jt10", 3,
        "Was unterscheidet Jesu Heilungen laut den Evangelien von bloßer Magie?",
        ["Jesus verwendete keine Zaubermittel, sondern nur Berührung und gesprochene Worte",
         "Jesus verknüpft Heilung mit Glauben, Würde und Sündenvergebung des Menschen",
         "Jesus vollbrachte Wunder nur im Verborgenen, ohne Zuschauer und Zeugen",
         "Jesus lehnte alle Heilungen ab, die ihm die Menge zuzuschreiben versuchte"],
        1,
        "In der Antike gab es viele Wundertäter und Magier. Das Besondere bei Jesus: Er heilt Menschen, die gesellschaftlich ausgeschlossen sind (Aussätzige, Zöllner, Frauen), spricht von Vergebung und fragt nach dem Glauben. »Dein Glaube hat dich gerettet« — das Heil ist tiefer als die körperliche Heilung. Die Wunder sind »Zeichen« des kommenden Gottesreiches.",
        None, None),
],

"gleichnisse": [
    mc("gl8", 1,
        "Im Gleichnis vom Verlorenen Sohn — was forderte der Sohn vom Vater?",
        ["Er bat den Vater, ihm einen festen Arbeitsplatz auf dem Hof zu geben",
         "Er forderte seinen Erbteil schon zu Lebzeiten des Vaters und zog fort",
         "Er fragte den Vater, ob er bei seinem Bruder in der Stadt wohnen dürfe",
         "Er bat den Vater um Geld für eine Wallfahrt nach Jerusalem"],
        1,
        "Der jüngere Sohn fordert seinen Erbteil, bevor der Vater gestorben ist — eine im Judentum unerhörte Anmaßung. Er verprasst alles in der Fremde. Als er zurückkommt, erwartet er nichts — doch der Vater läuft ihm entgegen, fällt ihm um den Hals und feiert. Das Gleichnis zeigt: Gott läuft uns entgegen, er wartet nicht, bis wir ankommen.",
        "Lk 15,11-32", "https://www.die-bibel.de/bibel/BB/LUK.15.11-LUK.15.32"),
    mc("gl9", 2,
        "Warum erzählte Jesus Gleichnisse statt direkter theologischer Aussagen?",
        ["Weil er keine theologische Ausbildung hatte und nicht abstrakt denken konnte",
         "Weil er bildhaft lehrte, damit alle Menschen — auch ohne Bildung — verstehen konnten",
         "Weil die Römer direkte religiöse Aussagen verboten und er sich schützen musste",
         "Weil die Jünger zu wenig Bibelwissen hatten und nur Geschichten verstanden"],
        1,
        "Gleichnisse sind meisterhafte Lehrform: Sie holen Menschen dort ab, wo sie leben — auf dem Feld, beim Kochen, im Weinberg. Gleichzeitig bleiben sie offen: Wer hören will, versteht mehr; wer verschlossen ist, hört nur eine Geschichte. Jesus selbst zitiert Jesaja: »Damit sie hören und doch nicht verstehen« (Mk 4,12) — Gleichnisse fordern Bereitschaft zur Umkehr.",
        None, None),
    mc("gl10", 3,
        "Was ist die Botschaft des Gleichnisses von den Arbeitern im Weinberg (Mt 20,1–16)?",
        ["Wer früh anfängt zu arbeiten, hat Anspruch auf mehr Lohn als die anderen",
         "Gottes Güte folgt keiner menschlichen Leistungsgerechtigkeit — alle erhalten das Gleiche",
         "Im Reich Gottes werden die besten Plätze für die Treuesten reserviert",
         "Arbeitgeber sollen ihre Mitarbeiter fair und nach Tarif entlohnen"],
        1,
        "Alle Arbeiter — ob seit dem Morgen oder erst seit einer Stunde tätig — erhalten denselben Lohn. Das empört die Frühanfänger. Der Weinbergbesitzer antwortet: »Bin ich nicht gütig, weil ich so großzügig bin?« Die Botschaft: Gottes Gnade ist kein Lohn, den man verdient. Sie ist ein Geschenk — für alle gleich.",
        "Mt 20,1-16", "https://www.die-bibel.de/bibel/BB/MAT.20.1-MAT.20.16"),
],

"gebote-bergpredigt": [
    mc("gb8", 1,
        "Auf welchem Berg empfing Mose die Zehn Gebote von Gott?",
        ["Berg Karmel in der Nähe von Haifa",
         "Berg Sinai auf der Halbinsel Sinai",
         "Berg Zion in Jerusalem",
         "Berg Tabor in Galiläa"],
        1,
        "Auf dem Berg Sinai (auch Horeb genannt) erschien Gott dem Mose im brennenden Dornbusch und gab ihm die Zehn Gebote auf zwei Steintafeln (2. Mose 20; 5. Mose 5). Der Berg gilt als heiliger Ort des Bundes zwischen Gott und seinem Volk. Bis heute pilgern Menschen dorthin.",
        "2 Mo 20,1-17", "https://www.die-bibel.de/bibel/BB/EXO.20.1-EXO.20.17"),
    mc("gb9", 2,
        "Was sagt Jesus in der Bergpredigt über das Gebot »Du sollst nicht töten«?",
        ["Das Gebot gilt nicht mehr, weil Jesus es durch das Liebesgebot aufgehoben hat",
         "Wer hasst oder beleidigt, verstößt bereits gegen Gottes Willen, nicht erst wer tötet",
         "Das Gebot bezieht sich nur auf Mord, nicht auf Krieg oder staatliche Todesstrafe",
         "Jesus erweitert das Gebot auf alle Lebewesen — auch Tiere darf man nicht töten"],
        1,
        "Jesus sagt: »Ihr habt gehört: Du sollst nicht töten. Ich aber sage euch: Wer seinem Bruder auch nur zürnt, ist dem Gericht verfallen« (Mt 5,21–22). Er radikalisiert die Gebote: Es geht nicht nur ums Äußere, sondern ums Herz. Hadern, Beleidigen, Verachten — das alles verletzt die Würde des anderen und widerspricht Gottes Willen.",
        "Mt 5,21-22", "https://www.die-bibel.de/bibel/BB/MAT.5.21-MAT.5.22"),
    mc("gb10", 3,
        "Was ist der Unterschied zwischen den Zehn Geboten und dem Liebesgebot Jesu?",
        ["Die Zehn Gebote stammen aus dem AT und gelten nicht mehr; das Liebesgebot ersetzt sie",
         "Die Zehn Gebote nennen konkrete Regeln; das Liebesgebot fasst alle Gebote zusammen und kommt aus dem Herzen",
         "Die Zehn Gebote richten sich an das Volk Israel; das Liebesgebot gilt nur für Christen",
         "Die Zehn Gebote sind verbindlich für alle; das Liebesgebot ist nur eine Empfehlung"],
        1,
        "Jesus hebt die Zehn Gebote nicht auf, sondern konzentriert sie: »Du sollst Gott lieben — und deinen Nächsten wie dich selbst. An diesen zwei Geboten hängt das ganze Gesetz« (Mt 22,37–40). Paulus schreibt: »Die Liebe ist des Gesetzes Erfüllung« (Röm 13,10). Die Gebote beschreiben von außen, was die Liebe von innen tut.",
        "Mt 22,37-40", "https://www.die-bibel.de/bibel/BB/MAT.22.37-MAT.22.40"),
],

"evangelische-kirche": [
    mc("ek8", 1,
        "Wo wurde Martin Luther geboren?",
        ["In Wittenberg an der Elbe, wo er später als Professor lehrte",
         "In Eisleben in Sachsen-Anhalt, im Jahr 1483",
         "In Erfurt in Thüringen, wo er später Theologie studierte",
         "In Mansfeld in Sachsen-Anhalt, wo er seine Kindheit verbrachte"],
        1,
        "Luther wurde am 10. November 1483 in Eisleben geboren — und starb dort auch 1546. Aufgewachsen ist er in Mansfeld, studiert hat er in Erfurt, als Mönch lebte er in Erfurt und Wittenberg. Als Reformator wirkte er vor allem in Wittenberg, wo er die 95 Thesen veröffentlichte.",
        None, None),
    mc("ek9", 2,
        "Was ist die »Confessio Augustana« von 1530?",
        ["Luthers Bibelübersetzung ins Deutsche, entstanden auf der Wartburg",
         "Das wichtigste Bekenntnis der lutherischen Reformation, vorgelegt dem Kaiser in Augsburg",
         "Die Zusammenfassung von Luthers 95 Thesen in lateinischer Sprache",
         "Der Friedensvertrag zwischen Lutheranern und Katholiken nach dem Bauernkrieg"],
        1,
        "Die Confessio Augustana (Augsburger Bekenntnis) wurde 1530 auf dem Reichstag zu Augsburg Kaiser Karl V. vorgelegt. Verfasst von Philipp Melanchthon, fasst sie den evangelischen Glauben in 28 Artikeln zusammen. Sie ist bis heute das grundlegende Bekenntnis der lutherischen Kirchen weltweit.",
        None, None),
    mc("ek10", 3,
        "Was bedeutet das Kürzel EKBO?",
        ["Evangelisch-Kirchliche Bildungsorganisation",
         "Evangelische Kirche Berlin-Brandenburg-schlesische Oberlausitz",
         "Evangelischer Kirchenbund Ostdeutschland",
         "Evangelische Konferenz für Bekenntnis und Ordnung"],
        1,
        "Die EKBO (Evangelische Kirche Berlin-Brandenburg-schlesische Oberlausitz) ist die Landeskirche, zu der die Evangelische Kirchengemeinde Staaken gehört. Sie entstand 2004 durch Zusammenschluss zweier Landeskirchen. Die EKBO ist ihrerseits Mitglied der EKD (Evangelische Kirche in Deutschland).",
        None, None),
],

"nur-fuer-profis": [
    mc("np8", 3,
        "Was ist »natürliche Theologie«?",
        ["Die Theologie, die sich ausschließlich mit Schöpfung und Ökologie befasst",
         "Der Versuch, Gott durch Vernunft und Naturbeobachtung ohne Offenbarung zu erkennen",
         "Die Methode, Bibelaussagen durch Naturwissenschaft zu überprüfen",
         "Die Lehre, dass Gott sich in der Natur vollständiger zeigt als in der Bibel"],
        1,
        "Natürliche Theologie fragt: Kann man Gott auch ohne Bibel erkennen — z. B. durch Vernunft oder Schöpfungsbetrachtung? Thomas von Aquin bejahte das. Karl Barth lehnte es radikal ab: Gott ist nur durch seine Selbstoffenbarung in Jesus Christus erkennbar. Der Streit ist bis heute nicht abgeschlossen.",
        None, None),
    mc("np9", 3,
        "Was ist der Unterschied zwischen Orthodoxie und Orthopraxie?",
        ["Orthodoxie bezeichnet die griechisch-orthodoxe Kirche; Orthopraxie die russisch-orthodoxe",
         "Orthodoxie meint rechtes Denken und Bekennen; Orthopraxie meint rechtes Handeln",
         "Orthodoxie ist die Lehre von der Auferstehung; Orthopraxie die Lehre vom Gebet",
         "Orthodoxie bezeichnet altgläubige Christen; Orthopraxie bezeichnet die Reformierten"],
        1,
        "Orthodoxie (griech. orthos = recht, doxa = Lehre) betont: Der rechte Glaube kommt im richtigen Bekennen zum Ausdruck. Orthopraxie (praxis = Handlung) betont: Der Glaube zeigt sich im richtigen Tun — in Gerechtigkeit, Barmherzigkeit, Gottesdienst. Die Reformatoren betonten: Glaube allein rettet — aber echter Glaube trägt Früchte. Jakobus 2,17: »Glaube ohne Werke ist tot.«",
        "Jak 2,17", "https://www.die-bibel.de/bibel/BB/JAS.2.17-JAS.2.17"),
    mc("np10", 3,
        "Was meint »Demythologisierung« bei Rudolf Bultmann?",
        ["Die Methode, alle Wundergeschichten der Bibel als historisch unzuverlässig zu streichen",
         "Das Programm, den Kern des Evangeliums aus dem mythologischen Weltbild des NT herauszuschälen",
         "Die Übersetzung biblischer Texte in moderne Sprache ohne theologische Fachbegriffe",
         "Die These, dass die Evangelien rein symbolische und keine historischen Dokumente sind"],
        1,
        "Rudolf Bultmann (1884–1976) argumentierte: Das NT ist in einem antiken Weltbild verfasst (Himmel oben, Hölle unten, Dämonen etc.), das heute niemand mehr teilt. Demythologisierung heißt: Den existenziellen Kern der Botschaft freilegen — nicht »Jesus ist aufgefahren«, sondern: Der Auferstandene begegnet mir heute. Bis heute heiß umstritten.",
        None, None),
],

"gemeinde-geschichte": [
    mc("gg8", 2,
        "Wer weihte am 30. Mai 1971 das Gemeindehaus an der Heerstraße Nord ein?",
        ["Superintendent Gerhard Niederstucke, der erste Pfarrer der Gemeinde",
         "Bischof Kurt Scharf, der damalige Bischof von Berlin",
         "Landesbischof Otto Dibelius, der frühere Bischof von Berlin",
         "Superintendent Hans-Martin Helbich vom Kirchenkreis Spandau"],
        1,
        "Bischof Kurt Scharf weihte das Gemeindehaus am Pillnitzer Weg 8 ein. Die Festpredigt hielt der Theologe Ernst Lange — nach ihm trägt das Haus heute seinen Namen. Hinweis: Diesen Namen trägt das Gebäude erst seit Kurzem; lange Zeit war es schlicht als »Gemeindehaus Heerstraße Nord« bekannt.",
        None, None),
    mc("gg9", 2,
        "Was stellt das Triptychon über dem Altar in der Kirche Heerstraße Nord dar?",
        ["Die Ausgießung des Heiligen Geistes an Pfingsten, gemalt von Siegmund Hahn",
         "Die Kreuzigung Jesu (1950), gemalt von Arthur Degner, einem Schüler von Lovis Corinth",
         "Das letzte Abendmahl Jesu mit seinen Jüngern, von einem Berliner Maler",
         "Die Auferstehung Jesu am Ostermorgen, von Helge Warme wie in der Dorfkirche"],
        1,
        "Das dreiteilige Altarbild zeigt die Kreuzigung Jesu und stammt von Arthur Degner (1875–1952), einem Schüler des berühmten Malers Lovis Corinth. Degner malte es 1950. Es hängt seit der Einweihung der Kirche 1976/78 über dem Altar und gehört zu den kunsthistorisch bemerkenswerten Stücken der Gemeinde.",
        None, None),
    mc("gg10", 3,
        "Wann wurde der Förderverein »Dachreiter Gartenstadt-Kirche e.V.« gegründet?",
        ["1971, anlässlich der Einweihung des Gemeindehauses Heerstraße Nord",
         "1988; er finanzierte Restaurierungen, Orgelrenovierung und die Glockenanlage (2005)",
         "1999, nach der Gemeindefusion zur Sicherung der Gartenstadt-Kirche",
         "2005, anlässlich des Starts von Laib & Seele im Ernst-Lange-Haus"],
        1,
        "Der Förderverein »Dachreiter Gartenstadt-Kirche e.V.« wurde 1988 gegründet und hat seitdem wichtige Projekte finanziert: die Restaurierung von Kanzel- und Altargemälden, die Orgelrenovierung, 2005 die Installation der automatischen Glockenanlage, 2021 die Erneuerung der Heizung und zuletzt die Außenrenovierung der Ziegelfugen. Ein Beispiel gelebten Ehrenamts.",
        None, None),
],

"gemeinde-aktuell": [
    mc("ga8", 1,
        "Wie lautet die Adresse des Gemeindebüros?",
        ["Nennhauser Damm 72, 13591 Berlin (Dorfkirche Alt-Staaken)",
         "Am Kirchplatz 3a, 13591 Berlin (Kirche Gartenstadt)",
         "Pillnitzer Weg 8, 13593 Berlin (Ernst-Lange-Haus)",
         "Obstallee 22e, 13593 Berlin (Kirche Heerstraße Nord)"],
        2,
        "Das Gemeindebüro ist im Ernst-Lange-Haus, Pillnitzer Weg 8, 13593 Berlin. Erreichbar montags bis freitags von 8 bis 13 Uhr, Tel. +49 30 322 944 510. Wer Kontakt aufnehmen möchte — z. B. wegen Taufe, Trauung, Bestattung oder einfach einem Gespräch — ist dort genau richtig.",
        None, None),
    mc("ga9", 2,
        "Wann fusionierten die heutigen Gemeindeteile zur Evangelischen Kirchengemeinde Staaken?",
        ["1990 mit der Wiedervereinigung, als Ost- und West-Berliner Gemeinden zusammenkamen",
         "In zwei Schritten: 1999 und 2025 — erst zur »Ev. Kirchengemeinde zu Staaken«, dann mit der Gartenstadt",
         "2005, anlässlich des 10-jährigen Bestehens von Laib & Seele im Ernst-Lange-Haus",
         "2012, zum 30-jährigen Jubiläum der Partnerschaft mit der Gemeinde in Tansania"],
        1,
        "1999 schlossen sich mehrere Gemeinden zur »Evangelischen Kirchengemeinde zu Staaken« zusammen. Daneben blieb die »Evangelische Kirchengemeinde Staaken-Gartenstadt« eigenständig. Seit 2025 gibt es nur noch eine gemeinsame Gemeinde: die »Evangelische Kirchengemeinde Staaken«. Solche Fusionen erfordern viel Vertrauen — und sind eine Chance zum Neuanfang.",
        None, None),
    mc("ga10", 3,
        "Wie viele Kindertagesstätten trägt die Evangelische Kirchengemeinde Staaken?",
        ["Zwei Kitas: Kita Arche Noah und Kita Staaken-Gartenstadt",
         "Drei Kitas: Kita Arche Noah (mit Waldkindergruppe), Kita Regenbogen und Kita Staaken-Gartenstadt",
         "Vier Kitas: Kita Arche Noah, Waldkindergruppe, Kita Regenbogen und Kita Staaken-Gartenstadt",
         "Fünf Kitas mit verschiedenen pädagogischen Schwerpunkten in ganz Staaken"],
        1,
        "Die Gemeinde trägt drei Kindertagesstätten: die Kita Arche Noah (zu der die Waldkindergruppe als besonderes Angebot gehört), die Kita Regenbogen und die Kita Staaken-Gartenstadt. Alle drei sind Teil des diakonischen Engagements der Gemeinde für Familien im Stadtteil — Kirche, die für die Jüngsten da ist.",
        None, None),
],

}

# Neue Bibelzitate pro Thema (je 2 zusätzliche)
neue_zitate = {
    "pfingsten": [
        zitat("Berauscht euch nicht mit Wein — sondern lasst euch vom Geist erfüllen und redet miteinander in Psalmen, Hymnen und geistlichen Liedern.", "Eph 5,18-19", "https://www.die-bibel.de/bibel/BB/EPH.5.18-EPH.5.19"),
        zitat("Ihr werdet die Kraft des Heiligen Geistes empfangen — und meine Zeugen sein.", "Apg 1,8", "https://www.die-bibel.de/bibel/BB/ACT.1.8-ACT.1.8"),
    ],
    "gemeinde": [
        zitat("Niemand lebe für sich selbst.", "Röm 14,7", "https://www.die-bibel.de/bibel/BB/ROM.14.7-ROM.14.7"),
        zitat("Bemüht euch, die Einheit des Geistes zu bewahren durch das Band des Friedens.", "Eph 4,3", "https://www.die-bibel.de/bibel/BB/EPH.4.3-EPH.4.3"),
    ],
    "bibel": [
        zitat("Das Wort ist dir sehr nahe — in deinem Mund und in deinem Herzen.", "5 Mo 30,14", "https://www.die-bibel.de/bibel/BB/DEU.30.14-DEU.30.14"),
        zitat("Lass das Wort Christi reichlich unter euch wohnen.", "Kol 3,16", "https://www.die-bibel.de/bibel/BB/COL.3.16-COL.3.16"),
    ],
    "jesus-historisch": [
        zitat("Er kam in sein Eigentum, und die Seinen nahmen ihn nicht auf.", "Joh 1,11", "https://www.die-bibel.de/bibel/BB/JHN.1.11-JHN.1.11"),
        zitat("Die Zeit ist erfüllt — das Reich Gottes ist nah. Kehrt um und glaubt dem Evangelium!", "Mk 1,15", "https://www.die-bibel.de/bibel/BB/MRK.1.15-MRK.1.15"),
    ],
    "jesus-christus": [
        zitat("Tod, wo ist dein Stachel? Hölle, wo ist dein Sieg?", "1 Kor 15,55", "https://www.die-bibel.de/bibel/BB/1CO.15.55-1CO.15.55"),
        zitat("Ich bin überzeugt, dass weder Tod noch Leben uns scheiden kann von der Liebe Gottes.", "Röm 8,38-39", "https://www.die-bibel.de/bibel/BB/ROM.8.38-ROM.8.39"),
    ],
    "jesu-worte": [
        zitat("Ich nenne euch nicht mehr Knechte, sondern Freunde.", "Joh 15,15", "https://www.die-bibel.de/bibel/BB/JHN.15.15-JHN.15.15"),
        zitat("Ich bin bei euch alle Tage bis ans Ende der Welt.", "Mt 28,20", "https://www.die-bibel.de/bibel/BB/MAT.28.20-MAT.28.20"),
    ],
    "jesu-taten": [
        zitat("Was bei Menschen unmöglich ist, ist bei Gott möglich.", "Lk 18,27", "https://www.die-bibel.de/bibel/BB/LUK.18.27-LUK.18.27"),
        zitat("Die Blinden sehen, die Lahmen gehen — und den Armen wird das Evangelium gepredigt.", "Lk 7,22", "https://www.die-bibel.de/bibel/BB/LUK.7.22-LUK.7.22"),
    ],
    "gleichnisse": [
        zitat("Im Himmel wird mehr Freude sein über einen Sünder, der umkehrt, als über neunundneunzig Gerechte.", "Lk 15,7", "https://www.die-bibel.de/bibel/BB/LUK.15.7-LUK.15.7"),
        zitat("Wer Ohren hat zu hören, der höre.", "Mk 4,9", "https://www.die-bibel.de/bibel/BB/MRK.4.9-MRK.4.9"),
    ],
    "gebote-bergpredigt": [
        zitat("Gerechtigkeit erhöht ein Volk.", "Spr 14,34", "https://www.die-bibel.de/bibel/BB/PRO.14.34-PRO.14.34"),
        zitat("Die Liebe ist des Gesetzes Erfüllung.", "Röm 13,10", "https://www.die-bibel.de/bibel/BB/ROM.13.10-ROM.13.10"),
    ],
    "evangelische-kirche": [
        zitat("Ein feste Burg ist unser Gott, ein gute Wehr und Waffen.", "Ps 46 — Martin Luther", "https://www.die-bibel.de/bibel/BB/PSA.46.2-PSA.46.2"),
        zitat("Durch Gnade seid ihr gerettet — durch Glauben, nicht aus euch selbst.", "Eph 2,8", "https://www.die-bibel.de/bibel/BB/EPH.2.8-EPH.2.8"),
    ],
    "nur-fuer-profis": [
        zitat("Meine Kraft vollendet sich in der Schwachheit.", "2 Kor 12,9", "https://www.die-bibel.de/bibel/BB/2CO.12.9-2CO.12.9"),
        zitat("Wer ist so weise und verständig unter euch?", "Jak 3,13", "https://www.die-bibel.de/bibel/BB/JAS.3.13-JAS.3.13"),
    ],
    "gemeinde-geschichte": [
        zitat("Fragt nach den alten Pfaden: Welches ist der gute Weg? Und geht ihn.", "Jer 6,16", "https://www.die-bibel.de/bibel/BB/JER.6.16-JER.6.16"),
        zitat("Wir sind Gottes Mitarbeiter; ihr seid Gottes Ackerfeld und Gottes Bau.", "1 Kor 3,9", "https://www.die-bibel.de/bibel/BB/1CO.3.9-1CO.3.9"),
    ],
    "gemeinde-aktuell": [
        zitat("Die Gemeinde wuchs und wandelte in der Furcht des Herrn.", "Apg 9,31", "https://www.die-bibel.de/bibel/BB/ACT.9.31-ACT.9.31"),
        zitat("Dient dem Herrn mit Freude!", "Ps 100,2", "https://www.die-bibel.de/bibel/BB/PSA.100.2-PSA.100.2"),
    ],
}

# Einbauen
for thema in data['themen']:
    tid = thema['id']
    if tid in neue_fragen:
        thema['fragen'].extend(neue_fragen[tid])
        print(f"Fragen: {thema['titel']} → {len(thema['fragen'])} Fragen")
    if tid in neue_zitate:
        thema['zitate'].extend(neue_zitate[tid])
        print(f"Zitate: {thema['titel']} → {len(thema['zitate'])} Zitate")

with open('data/fragen.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("\nFertig!")
for t in data['themen']:
    print(f"  {t['icon']} {t['titel']}: {len(t['fragen'])} Fragen, {len(t['zitate'])} Zitate")
